export const GET_CARS_REQUEST = "GET_CARS_REQUEST";
export const GET_CARS_SUCCESS = "GET_CARS_SUCCESS";
export const GET_CARS_FAIL = "GET_CARS_FAIL";

export const GET_USER_CARS_REQUEST = "GET_USER_CARS_REQUEST";
export const GET_USER_CARS_SUCCESS = "GET_USER_CARS_SUCCESS";
export const GET_USER_CARS_FAIL = "GET_USER_CARS_FAIL";

export const ADD_CAR_REQUEST = "ADD_CAR_REQUEST";
export const ADD_CAR_SUCCESS = "ADD_CAR_SUCCESS";
export const ADD_CAR_FAIL = "ADD_CAR_FAIL";

export const UPDATE_CAR_REQUEST = "UPDATE_CAR_REQUEST";
export const UPDATE_CAR_SUCCESS = "UPDATE_CAR_SUCCESS";
export const UPDATE_CAR_FAIL = "UPDATE_CAR_FAIL";

export const DELETE_CAR_REQUEST = "DELETE_CAR_REQUEST";
export const DELETE_CAR_SUCCESS = "DELETE_CAR_SUCCESS";
export const DELETE_CAR_FAIL = "DELETE_CAR_FAIL";

export const SEARCH_CAR_REQUEST = "SEARCH_CAR_REQUEST";
export const SEARCH_CAR_SUCCESS = "SEARCH_CAR_SUCCESS";
export const SEARCH_CAR_FAIL = "SEARCH_CAR_FAIL";

export const SET_DETAIL_CAR = "SET_DETAIL_CAR";
